package com.mycompany.resources;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Aryan Mehta
 */
public class chatItem extends javax.swing.JPanel {

    public chatItem() {
        initComponents();
        txt.setEditable(false);
        txt.setBackground(new Color(0,0,0,0));
        txt.setOpaque(false);
    }

    public void addText(String text){
        txt.setText(text);
    }
    
    public void setTime(String time){
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.setLayout(new FlowLayout(FlowLayout.RIGHT,0,0));
        layeredPane.setBorder(new EmptyBorder(0,5,10,5));
        JLabel label = new JLabel(time);
        label.setForeground(new Color(102,102,102));
        layeredPane.add(label);
        add(layeredPane);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new com.mycompany.SwingItems.AutoTextSize();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 10));
        txt.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        add(txt);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 1);
        super.paintComponent(g);
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.SwingItems.AutoTextSize txt;
    // End of variables declaration//GEN-END:variables
}
