package com.mycompany.resources;

import com.mycompany.dataPacks.PanelClickListener;
import com.mycompany.dataPacks.db_conn;
import com.mycompany.dataPacks.imageMethods;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Aryan Mehta
 */
public class contact_tab extends javax.swing.JPanel {

    private String username;
    private PanelClickListener listener;
    
    db_conn db_var = new db_conn();
    imageMethods im = new imageMethods();
    
    public contact_tab(String username) {
        initComponents();
        this.username = username;
        lbl_img.setSize(40,53);
        init();
    }

    public void init(){
        lbl_username.setText(username);
        Icon icon = im.getImage(lbl_img, username);
        if (icon != null) {
            lbl_img.setIcon(icon);
        } else {
            lbl_img.setText("Image not found");
        }
            lbl_user_status.setText("Online");
            lbl_msg_num.setVisible(false);
    }
    
    public void setPanelListener(PanelClickListener panelClickListener){
        this.listener = panelClickListener;
    }
    
    public void setMsgLabelVisible(boolean status){
        lbl_msg_num.setVisible(status);
    }
    
    public String getReceiverName(){
        return lbl_username.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_username = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        lbl_user_status = new javax.swing.JLabel();
        lbl_msg_num = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lbl_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_usernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_usernameMouseExited(evt);
            }
        });
        add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 7, 150, 30));

        lbl_img.setBackground(new java.awt.Color(255, 255, 255));
        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_img.setOpaque(true);
        add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 40, 58));

        lbl_user_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user_status.setText("Online");
        add(lbl_user_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 43, 70, -1));

        lbl_msg_num.setBackground(new java.awt.Color(0, 255, 0));
        lbl_msg_num.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_msg_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_msg_num.setOpaque(true);
        add(lbl_msg_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 17, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usernameMouseClicked
        if(listener!=null){
            listener.onPanelClick(username);
        }
    }//GEN-LAST:event_lbl_usernameMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(Color.WHITE);
    }//GEN-LAST:event_formMouseExited

    private void lbl_usernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usernameMouseEntered
        setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lbl_usernameMouseEntered

    private void lbl_usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usernameMouseExited
        setBackground(Color.WHITE);
    }//GEN-LAST:event_lbl_usernameMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_msg_num;
    private javax.swing.JLabel lbl_user_status;
    private javax.swing.JLabel lbl_username;
    // End of variables declaration//GEN-END:variables
}
