package com.mycompany.resources;

import com.mycompany.dataPacks.imageMethods;
import java.awt.event.ActionListener;

/**
 *
 * @author Aryan Mehta
 */
public class request_status_pan extends javax.swing.JPanel {

    private String username;
    
    private imageMethods im = new imageMethods();
    private ActionListener buttonActionListener1,buttonActionListener2;
    
    public request_status_pan(String username) {
        initComponents();
        this.username = username;
        init();
    }

    private void init(){
        lbl_profile_img.setSize(40,66);
        lbl_friend_username.setText(username);
        lbl_profile_img.setIcon(im.getImage(lbl_profile_img, username));
    }
    
    public void setActionListener_1(ActionListener actionListener){
        this.buttonActionListener1 = actionListener;
    }
    
    public void setActionListener_2(ActionListener actionListener){
        this.buttonActionListener2 = actionListener;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_reject = new javax.swing.JButton();
        btn_accept = new javax.swing.JButton();
        lbl_profile_img = new javax.swing.JLabel();
        lbl_friend_username = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_reject.setBackground(new java.awt.Color(51, 51, 255));
        btn_reject.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btn_reject.setForeground(new java.awt.Color(255, 255, 255));
        btn_reject.setText("Reject");
        btn_reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rejectActionPerformed(evt);
            }
        });

        btn_accept.setBackground(new java.awt.Color(255, 51, 51));
        btn_accept.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setText("Accept");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });

        lbl_profile_img.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        lbl_friend_username.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_profile_img, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_friend_username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_accept)
                    .addComponent(btn_reject))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_profile_img, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_friend_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btn_accept)
                .addGap(6, 6, 6)
                .addComponent(btn_reject))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        if(buttonActionListener1!=null){
            buttonActionListener1.actionPerformed(evt);
        }
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void btn_rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rejectActionPerformed
        if(buttonActionListener2!=null){
            buttonActionListener2.actionPerformed(evt);
        }
    }//GEN-LAST:event_btn_rejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_reject;
    private javax.swing.JLabel lbl_friend_username;
    private javax.swing.JLabel lbl_profile_img;
    // End of variables declaration//GEN-END:variables
}
